from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import os

def generate_pdf_report(score: int, risks: list, explanation: str, negotiation_email: str) -> str:
    """Generate a PDF report of the contract analysis"""
    
    # Create reports directory
    reports_dir = "backend/data/reports"
    os.makedirs(reports_dir, exist_ok=True)
    
    # Generate filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    pdf_path = f"{reports_dir}/ContractIQ_Report_{timestamp}.pdf"
    
    # Create PDF
    doc = SimpleDocTemplate(pdf_path, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#6366f1'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#1e293b'),
        spaceAfter=12,
        spaceBefore=20
    )
    
    # Title
    story.append(Paragraph("ContractIQ Analysis Report", title_style))
    story.append(Paragraph(f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", styles['Normal']))
    story.append(Spacer(1, 0.3*inch))
    
    # Score Section
    score_color = colors.HexColor('#10b981') if score > 80 else (colors.HexColor('#f59e0b') if score > 50 else colors.HexColor('#ef4444'))
    
    story.append(Paragraph("Safety Score", heading_style))
    score_data = [[f"{score}/100"]]
    score_table = Table(score_data, colWidths=[2*inch])
    score_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), score_color),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 36),
        ('PADDING', (0, 0), (-1, -1), 20),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 0.3*inch))
    
    # Interpretation
    if score > 80:
        interpretation = "✓ Low Risk - Contract appears fair and balanced"
    elif score > 50:
        interpretation = "⚠ Medium Risk - Review carefully before signing"
    else:
        interpretation = "✗ High Risk - Strongly recommend negotiation"
    
    story.append(Paragraph(interpretation, styles['Normal']))
    story.append(Spacer(1, 0.4*inch))
    
    # Risks Section
    if risks:
        story.append(Paragraph(f"Identified Risks ({len(risks)})", heading_style))
        
        for i, risk in enumerate(risks, 1):
            risk_text = f"<b>{i}. {risk['category']}</b> ({risk['severity']})<br/>"
            risk_text += f"{risk['finding']}<br/>"
            risk_text += f"<i>Reality Check: {risk['expectation_check']}</i>"
            story.append(Paragraph(risk_text, styles['Normal']))
            story.append(Spacer(1, 0.2*inch))
    
    story.append(PageBreak())
    
    # AI Assessment
    story.append(Paragraph("AI Assessment", heading_style))
    for paragraph in explanation.split('\n'):
        if paragraph.strip():
            story.append(Paragraph(paragraph, styles['Normal']))
            story.append(Spacer(1, 0.1*inch))
    
    story.append(Spacer(1, 0.3*inch))
    
    # Negotiation Strategy
    story.append(Paragraph("Negotiation Strategy", heading_style))
    for paragraph in negotiation_email.split('\n'):
        if paragraph.strip():
            story.append(Paragraph(paragraph, styles['Normal']))
            story.append(Spacer(1, 0.1*inch))
    
    # Footer
    story.append(Spacer(1, 0.5*inch))
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.grey,
        alignment=TA_CENTER
    )
    story.append(Paragraph("Generated by ContractIQ - AI-Powered Contract Analysis", footer_style))
    story.append(Paragraph("This report is for informational purposes only and does not constitute legal advice.", footer_style))
    
    # Build PDF
    doc.build(story)
    
    return pdf_path
