"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Share2, FileDown, Mail, Link as LinkIcon, Check } from "lucide-react";

interface ExportMenuProps {
    score: number;
    risks: any[];
    explanation: string;
    email: string;
}

export function ExportMenu({ score, risks, explanation, email }: ExportMenuProps) {
    const [isOpen, setIsOpen] = useState(false);
    const [copied, setCopied] = useState(false);

    const generateShareableLink = () => {
        // Create a shareable data object
        const data = {
            score,
            risks: risks.length,
            timestamp: Date.now()
        };

        // In production, this would create a real shareable link
        const link = `${window.location.origin}/share/${btoa(JSON.stringify(data))}`;
        navigator.clipboard.writeText(link);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const exportToGoogleDocs = () => {
        // Format content for Google Docs
        const content = `ContractIQ Analysis Report
    
Safety Score: ${score}/100

Identified Risks (${risks.length}):
${risks.map((r, i) => `${i + 1}. ${r.category} (${r.severity})
   ${r.finding}
   Reality Check: ${r.expectation_check}`).join('\n\n')}

AI Assessment:
${explanation}

Negotiation Strategy:
${email}

---
Generated by ContractIQ on ${new Date().toLocaleDateString()}
`;

        // Open Google Docs with pre-filled content
        const encodedContent = encodeURIComponent(content);
        window.open(`https://docs.google.com/document/create?title=ContractIQ_Analysis&body=${encodedContent}`, '_blank');
    };

    const exportToEmail = () => {
        const subject = encodeURIComponent('Contract Analysis Report');
        const body = encodeURIComponent(`Hi,

I've analyzed a contract using ContractIQ. Here are the results:

Safety Score: ${score}/100

${explanation}

Best regards`);

        window.location.href = `mailto:?subject=${subject}&body=${body}`;
    };

    const downloadAsText = () => {
        const content = `ContractIQ Analysis Report
Generated: ${new Date().toLocaleString()}

SAFETY SCORE: ${score}/100

IDENTIFIED RISKS (${risks.length}):
${risks.map((r, i) => `
${i + 1}. ${r.category} - ${r.severity}
   Finding: ${r.finding}
   Reality Check: ${r.expectation_check}
`).join('\n')}

AI ASSESSMENT:
${explanation}

NEGOTIATION STRATEGY:
${email}

---
This report was generated by ContractIQ - AI-Powered Contract Analysis
`;

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `ContractIQ_Analysis_${Date.now()}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div style={{ position: 'relative' }}>
            <button
                onClick={() => setIsOpen(!isOpen)}
                className="btn btn-secondary"
                style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '0.5rem'
                }}
            >
                <Share2 style={{ width: '18px', height: '18px' }} />
                <span>Export & Share</span>
            </button>

            {isOpen && (
                <>
                    {/* Backdrop */}
                    <div
                        onClick={() => setIsOpen(false)}
                        style={{
                            position: 'fixed',
                            inset: 0,
                            zIndex: 998
                        }}
                    />

                    {/* Menu */}
                    <motion.div
                        initial={{ opacity: 0, y: -10, scale: 0.95 }}
                        animate={{ opacity: 1, y: 0, scale: 1 }}
                        style={{
                            position: 'absolute',
                            top: 'calc(100% + 0.5rem)',
                            right: 0,
                            width: '280px',
                            background: 'rgba(17, 24, 39, 0.98)',
                            backdropFilter: 'blur(20px)',
                            border: '1px solid rgba(148, 163, 184, 0.2)',
                            borderRadius: '1rem',
                            padding: '0.5rem',
                            zIndex: 999,
                            boxShadow: '0 10px 40px rgba(0, 0, 0, 0.3)'
                        }}
                    >
                        <button
                            onClick={generateShareableLink}
                            style={{
                                width: '100%',
                                padding: '0.75rem 1rem',
                                background: 'transparent',
                                border: 'none',
                                borderRadius: '0.5rem',
                                color: '#e2e8f0',
                                fontSize: '0.875rem',
                                cursor: 'pointer',
                                display: 'flex',
                                alignItems: 'center',
                                gap: '0.75rem',
                                transition: 'background 0.2s',
                                textAlign: 'left'
                            }}
                            onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(99, 102, 241, 0.1)'}
                            onMouseLeave={(e) => e.currentTarget.style.background = 'transparent'}
                        >
                            {copied ? (
                                <Check style={{ width: '18px', height: '18px', color: '#10b981' }} />
                            ) : (
                                <LinkIcon style={{ width: '18px', height: '18px', color: '#6366f1' }} />
                            )}
                            <div>
                                <div style={{ fontWeight: '600' }}>
                                    {copied ? 'Link Copied!' : 'Copy Shareable Link'}
                                </div>
                                <div style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '2px' }}>
                                    Share with anyone
                                </div>
                            </div>
                        </button>

                        <button
                            onClick={exportToGoogleDocs}
                            style={{
                                width: '100%',
                                padding: '0.75rem 1rem',
                                background: 'transparent',
                                border: 'none',
                                borderRadius: '0.5rem',
                                color: '#e2e8f0',
                                fontSize: '0.875rem',
                                cursor: 'pointer',
                                display: 'flex',
                                alignItems: 'center',
                                gap: '0.75rem',
                                transition: 'background 0.2s',
                                textAlign: 'left'
                            }}
                            onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(99, 102, 241, 0.1)'}
                            onMouseLeave={(e) => e.currentTarget.style.background = 'transparent'}
                        >
                            <svg width="18" height="18" viewBox="0 0 24 24" fill="#4285f4">
                                <path d="M14.727 6.727H14V0H4.91c-.905 0-1.637.732-1.637 1.636v20.728c0 .904.732 1.636 1.636 1.636h14.182c.904 0 1.636-.732 1.636-1.636V7.455h-6.728c-.401 0-.727-.326-.727-.728zM16.5 13.5v1.636H7.364V13.5H16.5zm0 3.273v1.636H7.364v-1.636H16.5zm-4.091-6.546V8.591H7.364v1.636h5.045z" />
                            </svg>
                            <div>
                                <div style={{ fontWeight: '600' }}>Export to Google Docs</div>
                                <div style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '2px' }}>
                                    Open in new tab
                                </div>
                            </div>
                        </button>

                        <button
                            onClick={downloadAsText}
                            style={{
                                width: '100%',
                                padding: '0.75rem 1rem',
                                background: 'transparent',
                                border: 'none',
                                borderRadius: '0.5rem',
                                color: '#e2e8f0',
                                fontSize: '0.875rem',
                                cursor: 'pointer',
                                display: 'flex',
                                alignItems: 'center',
                                gap: '0.75rem',
                                transition: 'background 0.2s',
                                textAlign: 'left'
                            }}
                            onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(99, 102, 241, 0.1)'}
                            onMouseLeave={(e) => e.currentTarget.style.background = 'transparent'}
                        >
                            <FileDown style={{ width: '18px', height: '18px', color: '#8b5cf6' }} />
                            <div>
                                <div style={{ fontWeight: '600' }}>Download as Text</div>
                                <div style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '2px' }}>
                                    Save to your device
                                </div>
                            </div>
                        </button>

                        <button
                            onClick={exportToEmail}
                            style={{
                                width: '100%',
                                padding: '0.75rem 1rem',
                                background: 'transparent',
                                border: 'none',
                                borderRadius: '0.5rem',
                                color: '#e2e8f0',
                                fontSize: '0.875rem',
                                cursor: 'pointer',
                                display: 'flex',
                                alignItems: 'center',
                                gap: '0.75rem',
                                transition: 'background 0.2s',
                                textAlign: 'left'
                            }}
                            onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(99, 102, 241, 0.1)'}
                            onMouseLeave={(e) => e.currentTarget.style.background = 'transparent'}
                        >
                            <Mail style={{ width: '18px', height: '18px', color: '#ec4899' }} />
                            <div>
                                <div style={{ fontWeight: '600' }}>Send via Email</div>
                                <div style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '2px' }}>
                                    Open email client
                                </div>
                            </div>
                        </button>
                    </motion.div>
                </>
            )}
        </div>
    );
}
